[package]
name = "x11-screenshot"
version = "0.1.0"
authors = ["TheHellBox <thehellbox11@gmail.com>"]


[dependencies]
image = "0.16.0"
libc="0.2.33"

[dependencies.x11]
version = "2.16.0"
features = ["xlib"]
